spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jamataran/scc-cc-poc-properties.git
          clone-on-start: true
          force-pull: true
          searchPaths: '{application}/{profile}'
      uri: http://localhost:9191

server:
  port: 9191

logging:
  level:
    org:
      springframework:
        cloud: trace